modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "simplecom"
version = "${version}"
displayName = "SimpleCom Server"
authors = "xiaofan"
description = '''
SimpleCom 服务端模组，提供语音通信与信道切换功能。
配合 SimpleCom 客户端模组使用，支持 Forge 1.19.2 服务端。
'''
#logoFile = ""

[[dependencies.simplecom]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplecom]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplecom]]
modId = "architectury"
mandatory = true
versionRange = "[6.0,)"
ordering = "AFTER"
side = "BOTH"
